export enum EventType {
  TICKET_CREATED = 'TICKET_CREATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  PRIORITY_CHANGED = 'PRIORITY_CHANGED',
  CATEGORY_CHANGED = 'CATEGORY_CHANGED',
  ASSIGNED = 'ASSIGNED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  TICKET_CLOSED = 'TICKET_CLOSED',
}
